apiVersion: apps/v1
kind: Deployment
metadata:
  name: pet-care-deployment
spec:
  selector:
    matchLabels:
      app: pet-care
  template:
    metadata:
      labels:
        app: pet-care
    spec:
      containers:
      - name: pet-care
        image: <image_name>:<tag>
        env:
        - name: COSMOS_URI
          valueFrom:
            configMapKeyRef:
              name: pet-care-configmap
              key: cosmos_uri
        - name: COSMOS_KEY
          valueFrom:
            configMapKeyRef:
              name: pet-care-configmap
              key: cosmos_key
        - name: COSMOS_DB
          valueFrom:
            configMapKeyRef:
              name: pet-care-configmap
              key: cosmos_database
        - name: COSMOS_CONTAINER
          valueFrom:
            configMapKeyRef:
              name: pet-care-configmap
              key: cosmos_container
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8000
